/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.validation;

import com.example.validation.example.ExampleForm;
import com.example.validation.validator.MyOwnValidator;
import com.example.validation.validator.ValidationResult;

import java.util.List;

public class App {
  public static void main(String[] args) {
    MyOwnValidator validator = new MyOwnValidator();

    ExampleForm form = new ExampleForm("", "十八");

    List<ValidationResult> results = validator.validate(form);

    for (var result : results) {
      System.out.println(result.getFieldName() + ": " + result.getErrorMessage());
    }
  }
}
